// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: research-pillars/static/static.proto

package static

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProgramsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramsRequest) Reset() {
	*x = GetProgramsRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramsRequest) ProtoMessage() {}

func (x *GetProgramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramsRequest.ProtoReflect.Descriptor instead.
func (*GetProgramsRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{0}
}

type GetProgramsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Programs      []*structpb.Struct     `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramsResponse) Reset() {
	*x = GetProgramsResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramsResponse) ProtoMessage() {}

func (x *GetProgramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramsResponse.ProtoReflect.Descriptor instead.
func (*GetProgramsResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{1}
}

func (x *GetProgramsResponse) GetPrograms() []*structpb.Struct {
	if x != nil {
		return x.Programs
	}
	return nil
}

type GetProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramRequest) Reset() {
	*x = GetProgramRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramRequest) ProtoMessage() {}

func (x *GetProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramRequest.ProtoReflect.Descriptor instead.
func (*GetProgramRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{2}
}

func (x *GetProgramRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       *structpb.Struct       `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramResponse) Reset() {
	*x = GetProgramResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramResponse) ProtoMessage() {}

func (x *GetProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramResponse.ProtoReflect.Descriptor instead.
func (*GetProgramResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{3}
}

func (x *GetProgramResponse) GetProgram() *structpb.Struct {
	if x != nil {
		return x.Program
	}
	return nil
}

type GetProgramDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramDataRequest) Reset() {
	*x = GetProgramDataRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramDataRequest) ProtoMessage() {}

func (x *GetProgramDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramDataRequest.ProtoReflect.Descriptor instead.
func (*GetProgramDataRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{4}
}

func (x *GetProgramDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProgramDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Program        *structpb.Struct       `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	Surveys        []*structpb.Struct     `protobuf:"bytes,2,rep,name=surveys,proto3" json:"surveys,omitempty"`
	Questionnaires []*structpb.Struct     `protobuf:"bytes,3,rep,name=questionnaires,proto3" json:"questionnaires,omitempty"`
	Consents       []*structpb.Struct     `protobuf:"bytes,4,rep,name=consents,proto3" json:"consents,omitempty"`
	Routines       []*structpb.Struct     `protobuf:"bytes,5,rep,name=routines,proto3" json:"routines,omitempty"`
	Displays       []*structpb.Struct     `protobuf:"bytes,6,rep,name=displays,proto3" json:"displays,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProgramDataResponse) Reset() {
	*x = GetProgramDataResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramDataResponse) ProtoMessage() {}

func (x *GetProgramDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramDataResponse.ProtoReflect.Descriptor instead.
func (*GetProgramDataResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{5}
}

func (x *GetProgramDataResponse) GetProgram() *structpb.Struct {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *GetProgramDataResponse) GetSurveys() []*structpb.Struct {
	if x != nil {
		return x.Surveys
	}
	return nil
}

func (x *GetProgramDataResponse) GetQuestionnaires() []*structpb.Struct {
	if x != nil {
		return x.Questionnaires
	}
	return nil
}

func (x *GetProgramDataResponse) GetConsents() []*structpb.Struct {
	if x != nil {
		return x.Consents
	}
	return nil
}

func (x *GetProgramDataResponse) GetRoutines() []*structpb.Struct {
	if x != nil {
		return x.Routines
	}
	return nil
}

func (x *GetProgramDataResponse) GetDisplays() []*structpb.Struct {
	if x != nil {
		return x.Displays
	}
	return nil
}

type GetProgramUpdatedAtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramUpdatedAtRequest) Reset() {
	*x = GetProgramUpdatedAtRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramUpdatedAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramUpdatedAtRequest) ProtoMessage() {}

func (x *GetProgramUpdatedAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramUpdatedAtRequest.ProtoReflect.Descriptor instead.
func (*GetProgramUpdatedAtRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{6}
}

func (x *GetProgramUpdatedAtRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProgramUpdatedAtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt     string                 `protobuf:"bytes,1,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramUpdatedAtResponse) Reset() {
	*x = GetProgramUpdatedAtResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramUpdatedAtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramUpdatedAtResponse) ProtoMessage() {}

func (x *GetProgramUpdatedAtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramUpdatedAtResponse.ProtoReflect.Descriptor instead.
func (*GetProgramUpdatedAtResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{7}
}

func (x *GetProgramUpdatedAtResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSurveysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveysRequest) Reset() {
	*x = GetSurveysRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveysRequest) ProtoMessage() {}

func (x *GetSurveysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveysRequest.ProtoReflect.Descriptor instead.
func (*GetSurveysRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{8}
}

func (x *GetSurveysRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type GetSurveysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surveys       []*structpb.Struct     `protobuf:"bytes,1,rep,name=surveys,proto3" json:"surveys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveysResponse) Reset() {
	*x = GetSurveysResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveysResponse) ProtoMessage() {}

func (x *GetSurveysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveysResponse.ProtoReflect.Descriptor instead.
func (*GetSurveysResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{9}
}

func (x *GetSurveysResponse) GetSurveys() []*structpb.Struct {
	if x != nil {
		return x.Surveys
	}
	return nil
}

type GetSurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveyRequest) Reset() {
	*x = GetSurveyRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveyRequest) ProtoMessage() {}

func (x *GetSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveyRequest.ProtoReflect.Descriptor instead.
func (*GetSurveyRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{10}
}

func (x *GetSurveyRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetSurveyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSurveyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Survey        *structpb.Struct       `protobuf:"bytes,1,opt,name=survey,proto3" json:"survey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveyResponse) Reset() {
	*x = GetSurveyResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveyResponse) ProtoMessage() {}

func (x *GetSurveyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveyResponse.ProtoReflect.Descriptor instead.
func (*GetSurveyResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{11}
}

func (x *GetSurveyResponse) GetSurvey() *structpb.Struct {
	if x != nil {
		return x.Survey
	}
	return nil
}

type GetQuestionnairesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionnairesRequest) Reset() {
	*x = GetQuestionnairesRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionnairesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnairesRequest) ProtoMessage() {}

func (x *GetQuestionnairesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnairesRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionnairesRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{12}
}

func (x *GetQuestionnairesRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetQuestionnairesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetQuestionnairesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Questionnaires []*structpb.Struct     `protobuf:"bytes,1,rep,name=questionnaires,proto3" json:"questionnaires,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuestionnairesResponse) Reset() {
	*x = GetQuestionnairesResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionnairesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnairesResponse) ProtoMessage() {}

func (x *GetQuestionnairesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnairesResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionnairesResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{13}
}

func (x *GetQuestionnairesResponse) GetQuestionnaires() []*structpb.Struct {
	if x != nil {
		return x.Questionnaires
	}
	return nil
}

type GetQuestionnaireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionnaireRequest) Reset() {
	*x = GetQuestionnaireRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionnaireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnaireRequest) ProtoMessage() {}

func (x *GetQuestionnaireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnaireRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionnaireRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{14}
}

func (x *GetQuestionnaireRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetQuestionnaireRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetQuestionnaireRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetQuestionnaireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questionnaire *structpb.Struct       `protobuf:"bytes,1,opt,name=questionnaire,proto3" json:"questionnaire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionnaireResponse) Reset() {
	*x = GetQuestionnaireResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionnaireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnaireResponse) ProtoMessage() {}

func (x *GetQuestionnaireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnaireResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionnaireResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{15}
}

func (x *GetQuestionnaireResponse) GetQuestionnaire() *structpb.Struct {
	if x != nil {
		return x.Questionnaire
	}
	return nil
}

type GetRoutinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutinesRequest) Reset() {
	*x = GetRoutinesRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutinesRequest) ProtoMessage() {}

func (x *GetRoutinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutinesRequest.ProtoReflect.Descriptor instead.
func (*GetRoutinesRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{16}
}

func (x *GetRoutinesRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type GetRoutinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routines      []*structpb.Struct     `protobuf:"bytes,1,rep,name=routines,proto3" json:"routines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutinesResponse) Reset() {
	*x = GetRoutinesResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutinesResponse) ProtoMessage() {}

func (x *GetRoutinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutinesResponse.ProtoReflect.Descriptor instead.
func (*GetRoutinesResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{17}
}

func (x *GetRoutinesResponse) GetRoutines() []*structpb.Struct {
	if x != nil {
		return x.Routines
	}
	return nil
}

type GetRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineRequest) Reset() {
	*x = GetRoutineRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineRequest) ProtoMessage() {}

func (x *GetRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineRequest.ProtoReflect.Descriptor instead.
func (*GetRoutineRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{18}
}

func (x *GetRoutineRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetRoutineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *structpb.Struct       `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineResponse) Reset() {
	*x = GetRoutineResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineResponse) ProtoMessage() {}

func (x *GetRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineResponse.ProtoReflect.Descriptor instead.
func (*GetRoutineResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{19}
}

func (x *GetRoutineResponse) GetRoutine() *structpb.Struct {
	if x != nil {
		return x.Routine
	}
	return nil
}

type GetDisplaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisplaysRequest) Reset() {
	*x = GetDisplaysRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplaysRequest) ProtoMessage() {}

func (x *GetDisplaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplaysRequest.ProtoReflect.Descriptor instead.
func (*GetDisplaysRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{20}
}

func (x *GetDisplaysRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type GetDisplaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Displays      []*structpb.Struct     `protobuf:"bytes,1,rep,name=displays,proto3" json:"displays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisplaysResponse) Reset() {
	*x = GetDisplaysResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplaysResponse) ProtoMessage() {}

func (x *GetDisplaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplaysResponse.ProtoReflect.Descriptor instead.
func (*GetDisplaysResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{21}
}

func (x *GetDisplaysResponse) GetDisplays() []*structpb.Struct {
	if x != nil {
		return x.Displays
	}
	return nil
}

type GetDisplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisplayRequest) Reset() {
	*x = GetDisplayRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplayRequest) ProtoMessage() {}

func (x *GetDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplayRequest.ProtoReflect.Descriptor instead.
func (*GetDisplayRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{22}
}

func (x *GetDisplayRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetDisplayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDisplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       *structpb.Struct       `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisplayResponse) Reset() {
	*x = GetDisplayResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplayResponse) ProtoMessage() {}

func (x *GetDisplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplayResponse.ProtoReflect.Descriptor instead.
func (*GetDisplayResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{23}
}

func (x *GetDisplayResponse) GetDisplay() *structpb.Struct {
	if x != nil {
		return x.Display
	}
	return nil
}

type GetConsentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsentsRequest) Reset() {
	*x = GetConsentsRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsentsRequest) ProtoMessage() {}

func (x *GetConsentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsentsRequest.ProtoReflect.Descriptor instead.
func (*GetConsentsRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{24}
}

func (x *GetConsentsRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type GetConsentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consents      []*structpb.Struct     `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsentsResponse) Reset() {
	*x = GetConsentsResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsentsResponse) ProtoMessage() {}

func (x *GetConsentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsentsResponse.ProtoReflect.Descriptor instead.
func (*GetConsentsResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{25}
}

func (x *GetConsentsResponse) GetConsents() []*structpb.Struct {
	if x != nil {
		return x.Consents
	}
	return nil
}

type GetConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsentRequest) Reset() {
	*x = GetConsentRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsentRequest) ProtoMessage() {}

func (x *GetConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsentRequest.ProtoReflect.Descriptor instead.
func (*GetConsentRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{26}
}

func (x *GetConsentRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetConsentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consents      []*structpb.Struct     `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsentResponse) Reset() {
	*x = GetConsentResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsentResponse) ProtoMessage() {}

func (x *GetConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsentResponse.ProtoReflect.Descriptor instead.
func (*GetConsentResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{27}
}

func (x *GetConsentResponse) GetConsents() []*structpb.Struct {
	if x != nil {
		return x.Consents
	}
	return nil
}

type GetConsentVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsentVersionRequest) Reset() {
	*x = GetConsentVersionRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsentVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsentVersionRequest) ProtoMessage() {}

func (x *GetConsentVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsentVersionRequest.ProtoReflect.Descriptor instead.
func (*GetConsentVersionRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{28}
}

func (x *GetConsentVersionRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetConsentVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetConsentVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetConsentVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consent       *structpb.Struct       `protobuf:"bytes,1,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsentVersionResponse) Reset() {
	*x = GetConsentVersionResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsentVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsentVersionResponse) ProtoMessage() {}

func (x *GetConsentVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsentVersionResponse.ProtoReflect.Descriptor instead.
func (*GetConsentVersionResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{29}
}

func (x *GetConsentVersionResponse) GetConsent() *structpb.Struct {
	if x != nil {
		return x.Consent
	}
	return nil
}

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	ProgramName   string                 `protobuf:"bytes,3,opt,name=programName,proto3" json:"programName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{30}
}

func (x *ProxyRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProxyRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProxyRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *structpb.Struct       `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{31}
}

func (x *ProxyResponse) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramName   string                 `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{32}
}

func (x *GetImageRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *GetImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksRequest) Reset() {
	*x = ChecksRequest{}
	mi := &file_research_pillars_static_static_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksRequest) ProtoMessage() {}

func (x *ChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksRequest.ProtoReflect.Descriptor instead.
func (*ChecksRequest) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{33}
}

type ChecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksResponse) Reset() {
	*x = ChecksResponse{}
	mi := &file_research_pillars_static_static_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksResponse) ProtoMessage() {}

func (x *ChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_research_pillars_static_static_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksResponse.ProtoReflect.Descriptor instead.
func (*ChecksResponse) Descriptor() ([]byte, []int) {
	return file_research_pillars_static_static_proto_rawDescGZIP(), []int{34}
}

func (x *ChecksResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_research_pillars_static_static_proto protoreflect.FileDescriptor

const file_research_pillars_static_static_proto_rawDesc = "" +
	"\n" +
	"$research-pillars/static/static.proto\x12\fproto.static\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x14\n" +
	"\x12GetProgramsRequest\"J\n" +
	"\x13GetProgramsResponse\x123\n" +
	"\bprograms\x18\x01 \x03(\v2\x17.google.protobuf.StructR\bprograms\"'\n" +
	"\x11GetProgramRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x12GetProgramResponse\x121\n" +
	"\aprogram\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aprogram\"+\n" +
	"\x15GetProgramDataRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xde\x02\n" +
	"\x16GetProgramDataResponse\x121\n" +
	"\aprogram\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aprogram\x121\n" +
	"\asurveys\x18\x02 \x03(\v2\x17.google.protobuf.StructR\asurveys\x12?\n" +
	"\x0equestionnaires\x18\x03 \x03(\v2\x17.google.protobuf.StructR\x0equestionnaires\x123\n" +
	"\bconsents\x18\x04 \x03(\v2\x17.google.protobuf.StructR\bconsents\x123\n" +
	"\broutines\x18\x05 \x03(\v2\x17.google.protobuf.StructR\broutines\x123\n" +
	"\bdisplays\x18\x06 \x03(\v2\x17.google.protobuf.StructR\bdisplays\"0\n" +
	"\x1aGetProgramUpdatedAtRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x1bGetProgramUpdatedAtResponse\x12\x1c\n" +
	"\tupdatedAt\x18\x01 \x01(\tR\tupdatedAt\"5\n" +
	"\x11GetSurveysRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\"G\n" +
	"\x12GetSurveysResponse\x121\n" +
	"\asurveys\x18\x01 \x03(\v2\x17.google.protobuf.StructR\asurveys\"H\n" +
	"\x10GetSurveyRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x11GetSurveyResponse\x12/\n" +
	"\x06survey\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06survey\"X\n" +
	"\x18GetQuestionnairesRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\\\n" +
	"\x19GetQuestionnairesResponse\x12?\n" +
	"\x0equestionnaires\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x0equestionnaires\"k\n" +
	"\x17GetQuestionnaireRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"Y\n" +
	"\x18GetQuestionnaireResponse\x12=\n" +
	"\rquestionnaire\x18\x01 \x01(\v2\x17.google.protobuf.StructR\rquestionnaire\"6\n" +
	"\x12GetRoutinesRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\"J\n" +
	"\x13GetRoutinesResponse\x123\n" +
	"\broutines\x18\x01 \x03(\v2\x17.google.protobuf.StructR\broutines\"I\n" +
	"\x11GetRoutineRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\x12GetRoutineResponse\x121\n" +
	"\aroutine\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aroutine\"6\n" +
	"\x12GetDisplaysRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\"J\n" +
	"\x13GetDisplaysResponse\x123\n" +
	"\bdisplays\x18\x01 \x03(\v2\x17.google.protobuf.StructR\bdisplays\"I\n" +
	"\x11GetDisplayRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\x12GetDisplayResponse\x121\n" +
	"\adisplay\x18\x01 \x01(\v2\x17.google.protobuf.StructR\adisplay\"6\n" +
	"\x12GetConsentsRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\"J\n" +
	"\x13GetConsentsResponse\x123\n" +
	"\bconsents\x18\x01 \x03(\v2\x17.google.protobuf.StructR\bconsents\"I\n" +
	"\x11GetConsentRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"I\n" +
	"\x12GetConsentResponse\x123\n" +
	"\bconsents\x18\x01 \x03(\v2\x17.google.protobuf.StructR\bconsents\"j\n" +
	"\x18GetConsentVersionRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"N\n" +
	"\x19GetConsentVersionResponse\x121\n" +
	"\aconsent\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aconsent\"y\n" +
	"\fProxyRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x12 \n" +
	"\vprogramName\x18\x03 \x01(\tR\vprogramName\"<\n" +
	"\rProxyResponse\x12+\n" +
	"\x04body\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04body\"G\n" +
	"\x0fGetImageRequest\x12 \n" +
	"\vprogramName\x18\x01 \x01(\tR\vprogramName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x0f\n" +
	"\rChecksRequest\",\n" +
	"\x0eChecksResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\xe9\x03\n" +
	"\bPrograms\x12e\n" +
	"\vGetPrograms\x12 .proto.static.GetProgramsRequest\x1a!.proto.static.GetProgramsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/programs\x12i\n" +
	"\n" +
	"GetProgram\x12\x1f.proto.static.GetProgramRequest\x1a .proto.static.GetProgramResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/programs/{name}\x12z\n" +
	"\x0eGetProgramData\x12#.proto.static.GetProgramDataRequest\x1a$.proto.static.GetProgramDataResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/programs/{name}/data\x12\x8e\x01\n" +
	"\x13GetProgramUpdatedAt\x12(.proto.static.GetProgramUpdatedAtRequest\x1a).proto.static.GetProgramUpdatedAtResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/programs/{name}/updatedAt2\x81\x02\n" +
	"\aSurveys\x12x\n" +
	"\n" +
	"GetSurveys\x12\x1f.proto.static.GetSurveysRequest\x1a .proto.static.GetSurveysResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/programs/{programName}/surveys\x12|\n" +
	"\tGetSurvey\x12\x1e.proto.static.GetSurveyRequest\x1a\x1f.proto.static.GetSurveyResponse\".\x82\xd3\xe4\x93\x02(\x12&/programs/{programName}/surveys/{name}2\xc2\x02\n" +
	"\x0eQuestionnaires\x12\x94\x01\n" +
	"\x11GetQuestionnaires\x12&.proto.static.GetQuestionnairesRequest\x1a'.proto.static.GetQuestionnairesResponse\".\x82\xd3\xe4\x93\x02(\x12&/programs/{programName}/questionnaires\x12\x98\x01\n" +
	"\x10GetQuestionnaire\x12%.proto.static.GetQuestionnaireRequest\x1a&.proto.static.GetQuestionnaireResponse\"5\x82\xd3\xe4\x93\x02/\x12-/programs/{programName}/questionnaires/{name}2\x8b\x02\n" +
	"\bRoutines\x12|\n" +
	"\vGetRoutines\x12 .proto.static.GetRoutinesRequest\x1a!.proto.static.GetRoutinesResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /programs/{programName}/routines\x12\x80\x01\n" +
	"\n" +
	"GetRoutine\x12\x1f.proto.static.GetRoutineRequest\x1a .proto.static.GetRoutineResponse\"/\x82\xd3\xe4\x93\x02)\x12'/programs/{programName}/routines/{name}2\x8b\x02\n" +
	"\bDisplays\x12|\n" +
	"\vGetDisplays\x12 .proto.static.GetDisplaysRequest\x1a!.proto.static.GetDisplaysResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /programs/{programName}/displays\x12\x80\x01\n" +
	"\n" +
	"GetDisplay\x12\x1f.proto.static.GetDisplayRequest\x1a .proto.static.GetDisplayResponse\"/\x82\xd3\xe4\x93\x02)\x12'/programs/{programName}/displays/{name}2\xad\x03\n" +
	"\bConsents\x12|\n" +
	"\vGetConsents\x12 .proto.static.GetConsentsRequest\x1a!.proto.static.GetConsentsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /programs/{programName}/consents\x12\x80\x01\n" +
	"\n" +
	"GetConsent\x12\x1f.proto.static.GetConsentRequest\x1a .proto.static.GetConsentResponse\"/\x82\xd3\xe4\x93\x02)\x12'/programs/{programName}/consents/{name}\x12\x9f\x01\n" +
	"\x11GetConsentVersion\x12&.proto.static.GetConsentVersionRequest\x1a'.proto.static.GetConsentVersionResponse\"9\x82\xd3\xe4\x93\x023\x121/programs/{programName}/consents/{name}/{version}2j\n" +
	"\tUtilities\x12]\n" +
	"\x05Proxy\x12\x1a.proto.static.ProxyRequest\x1a\x1b.proto.static.ProxyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/utilities/proxy2x\n" +
	"\x06Images\x12n\n" +
	"\bGetImage\x12\x1d.proto.static.GetImageRequest\x1a\x14.google.api.HttpBody\"-\x82\xd3\xe4\x93\x02'\x12%/programs/{programName}/images/{name}2\xcc\x01\n" +
	"\x06Checks\x12_\n" +
	"\bLiveness\x12\x1b.proto.static.ChecksRequest\x1a\x1c.proto.static.ChecksResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/checks/liveness\x12a\n" +
	"\tReadiness\x12\x1b.proto.static.ChecksRequest\x1a\x1c.proto.static.ChecksResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/checks/readinessB\x97\x01\x92AQ\x12O\n" +
	"\x14Research Pillars API\"2\n" +
	"\x18Research Enablement Team\x12\x16https://data4life.care2\x031.0ZAgithub.com/d4l-data4life/grpc-modules/pkg/research-pillars/staticb\x06proto3"

var (
	file_research_pillars_static_static_proto_rawDescOnce sync.Once
	file_research_pillars_static_static_proto_rawDescData []byte
)

func file_research_pillars_static_static_proto_rawDescGZIP() []byte {
	file_research_pillars_static_static_proto_rawDescOnce.Do(func() {
		file_research_pillars_static_static_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_research_pillars_static_static_proto_rawDesc), len(file_research_pillars_static_static_proto_rawDesc)))
	})
	return file_research_pillars_static_static_proto_rawDescData
}

var file_research_pillars_static_static_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_research_pillars_static_static_proto_goTypes = []any{
	(*GetProgramsRequest)(nil),          // 0: proto.static.GetProgramsRequest
	(*GetProgramsResponse)(nil),         // 1: proto.static.GetProgramsResponse
	(*GetProgramRequest)(nil),           // 2: proto.static.GetProgramRequest
	(*GetProgramResponse)(nil),          // 3: proto.static.GetProgramResponse
	(*GetProgramDataRequest)(nil),       // 4: proto.static.GetProgramDataRequest
	(*GetProgramDataResponse)(nil),      // 5: proto.static.GetProgramDataResponse
	(*GetProgramUpdatedAtRequest)(nil),  // 6: proto.static.GetProgramUpdatedAtRequest
	(*GetProgramUpdatedAtResponse)(nil), // 7: proto.static.GetProgramUpdatedAtResponse
	(*GetSurveysRequest)(nil),           // 8: proto.static.GetSurveysRequest
	(*GetSurveysResponse)(nil),          // 9: proto.static.GetSurveysResponse
	(*GetSurveyRequest)(nil),            // 10: proto.static.GetSurveyRequest
	(*GetSurveyResponse)(nil),           // 11: proto.static.GetSurveyResponse
	(*GetQuestionnairesRequest)(nil),    // 12: proto.static.GetQuestionnairesRequest
	(*GetQuestionnairesResponse)(nil),   // 13: proto.static.GetQuestionnairesResponse
	(*GetQuestionnaireRequest)(nil),     // 14: proto.static.GetQuestionnaireRequest
	(*GetQuestionnaireResponse)(nil),    // 15: proto.static.GetQuestionnaireResponse
	(*GetRoutinesRequest)(nil),          // 16: proto.static.GetRoutinesRequest
	(*GetRoutinesResponse)(nil),         // 17: proto.static.GetRoutinesResponse
	(*GetRoutineRequest)(nil),           // 18: proto.static.GetRoutineRequest
	(*GetRoutineResponse)(nil),          // 19: proto.static.GetRoutineResponse
	(*GetDisplaysRequest)(nil),          // 20: proto.static.GetDisplaysRequest
	(*GetDisplaysResponse)(nil),         // 21: proto.static.GetDisplaysResponse
	(*GetDisplayRequest)(nil),           // 22: proto.static.GetDisplayRequest
	(*GetDisplayResponse)(nil),          // 23: proto.static.GetDisplayResponse
	(*GetConsentsRequest)(nil),          // 24: proto.static.GetConsentsRequest
	(*GetConsentsResponse)(nil),         // 25: proto.static.GetConsentsResponse
	(*GetConsentRequest)(nil),           // 26: proto.static.GetConsentRequest
	(*GetConsentResponse)(nil),          // 27: proto.static.GetConsentResponse
	(*GetConsentVersionRequest)(nil),    // 28: proto.static.GetConsentVersionRequest
	(*GetConsentVersionResponse)(nil),   // 29: proto.static.GetConsentVersionResponse
	(*ProxyRequest)(nil),                // 30: proto.static.ProxyRequest
	(*ProxyResponse)(nil),               // 31: proto.static.ProxyResponse
	(*GetImageRequest)(nil),             // 32: proto.static.GetImageRequest
	(*ChecksRequest)(nil),               // 33: proto.static.ChecksRequest
	(*ChecksResponse)(nil),              // 34: proto.static.ChecksResponse
	(*structpb.Struct)(nil),             // 35: google.protobuf.Struct
	(*httpbody.HttpBody)(nil),           // 36: google.api.HttpBody
}
var file_research_pillars_static_static_proto_depIdxs = []int32{
	35, // 0: proto.static.GetProgramsResponse.programs:type_name -> google.protobuf.Struct
	35, // 1: proto.static.GetProgramResponse.program:type_name -> google.protobuf.Struct
	35, // 2: proto.static.GetProgramDataResponse.program:type_name -> google.protobuf.Struct
	35, // 3: proto.static.GetProgramDataResponse.surveys:type_name -> google.protobuf.Struct
	35, // 4: proto.static.GetProgramDataResponse.questionnaires:type_name -> google.protobuf.Struct
	35, // 5: proto.static.GetProgramDataResponse.consents:type_name -> google.protobuf.Struct
	35, // 6: proto.static.GetProgramDataResponse.routines:type_name -> google.protobuf.Struct
	35, // 7: proto.static.GetProgramDataResponse.displays:type_name -> google.protobuf.Struct
	35, // 8: proto.static.GetSurveysResponse.surveys:type_name -> google.protobuf.Struct
	35, // 9: proto.static.GetSurveyResponse.survey:type_name -> google.protobuf.Struct
	35, // 10: proto.static.GetQuestionnairesResponse.questionnaires:type_name -> google.protobuf.Struct
	35, // 11: proto.static.GetQuestionnaireResponse.questionnaire:type_name -> google.protobuf.Struct
	35, // 12: proto.static.GetRoutinesResponse.routines:type_name -> google.protobuf.Struct
	35, // 13: proto.static.GetRoutineResponse.routine:type_name -> google.protobuf.Struct
	35, // 14: proto.static.GetDisplaysResponse.displays:type_name -> google.protobuf.Struct
	35, // 15: proto.static.GetDisplayResponse.display:type_name -> google.protobuf.Struct
	35, // 16: proto.static.GetConsentsResponse.consents:type_name -> google.protobuf.Struct
	35, // 17: proto.static.GetConsentResponse.consents:type_name -> google.protobuf.Struct
	35, // 18: proto.static.GetConsentVersionResponse.consent:type_name -> google.protobuf.Struct
	35, // 19: proto.static.ProxyRequest.params:type_name -> google.protobuf.Struct
	35, // 20: proto.static.ProxyResponse.body:type_name -> google.protobuf.Struct
	0,  // 21: proto.static.Programs.GetPrograms:input_type -> proto.static.GetProgramsRequest
	2,  // 22: proto.static.Programs.GetProgram:input_type -> proto.static.GetProgramRequest
	4,  // 23: proto.static.Programs.GetProgramData:input_type -> proto.static.GetProgramDataRequest
	6,  // 24: proto.static.Programs.GetProgramUpdatedAt:input_type -> proto.static.GetProgramUpdatedAtRequest
	8,  // 25: proto.static.Surveys.GetSurveys:input_type -> proto.static.GetSurveysRequest
	10, // 26: proto.static.Surveys.GetSurvey:input_type -> proto.static.GetSurveyRequest
	12, // 27: proto.static.Questionnaires.GetQuestionnaires:input_type -> proto.static.GetQuestionnairesRequest
	14, // 28: proto.static.Questionnaires.GetQuestionnaire:input_type -> proto.static.GetQuestionnaireRequest
	16, // 29: proto.static.Routines.GetRoutines:input_type -> proto.static.GetRoutinesRequest
	18, // 30: proto.static.Routines.GetRoutine:input_type -> proto.static.GetRoutineRequest
	20, // 31: proto.static.Displays.GetDisplays:input_type -> proto.static.GetDisplaysRequest
	22, // 32: proto.static.Displays.GetDisplay:input_type -> proto.static.GetDisplayRequest
	24, // 33: proto.static.Consents.GetConsents:input_type -> proto.static.GetConsentsRequest
	26, // 34: proto.static.Consents.GetConsent:input_type -> proto.static.GetConsentRequest
	28, // 35: proto.static.Consents.GetConsentVersion:input_type -> proto.static.GetConsentVersionRequest
	30, // 36: proto.static.Utilities.Proxy:input_type -> proto.static.ProxyRequest
	32, // 37: proto.static.Images.GetImage:input_type -> proto.static.GetImageRequest
	33, // 38: proto.static.Checks.Liveness:input_type -> proto.static.ChecksRequest
	33, // 39: proto.static.Checks.Readiness:input_type -> proto.static.ChecksRequest
	1,  // 40: proto.static.Programs.GetPrograms:output_type -> proto.static.GetProgramsResponse
	3,  // 41: proto.static.Programs.GetProgram:output_type -> proto.static.GetProgramResponse
	5,  // 42: proto.static.Programs.GetProgramData:output_type -> proto.static.GetProgramDataResponse
	7,  // 43: proto.static.Programs.GetProgramUpdatedAt:output_type -> proto.static.GetProgramUpdatedAtResponse
	9,  // 44: proto.static.Surveys.GetSurveys:output_type -> proto.static.GetSurveysResponse
	11, // 45: proto.static.Surveys.GetSurvey:output_type -> proto.static.GetSurveyResponse
	13, // 46: proto.static.Questionnaires.GetQuestionnaires:output_type -> proto.static.GetQuestionnairesResponse
	15, // 47: proto.static.Questionnaires.GetQuestionnaire:output_type -> proto.static.GetQuestionnaireResponse
	17, // 48: proto.static.Routines.GetRoutines:output_type -> proto.static.GetRoutinesResponse
	19, // 49: proto.static.Routines.GetRoutine:output_type -> proto.static.GetRoutineResponse
	21, // 50: proto.static.Displays.GetDisplays:output_type -> proto.static.GetDisplaysResponse
	23, // 51: proto.static.Displays.GetDisplay:output_type -> proto.static.GetDisplayResponse
	25, // 52: proto.static.Consents.GetConsents:output_type -> proto.static.GetConsentsResponse
	27, // 53: proto.static.Consents.GetConsent:output_type -> proto.static.GetConsentResponse
	29, // 54: proto.static.Consents.GetConsentVersion:output_type -> proto.static.GetConsentVersionResponse
	31, // 55: proto.static.Utilities.Proxy:output_type -> proto.static.ProxyResponse
	36, // 56: proto.static.Images.GetImage:output_type -> google.api.HttpBody
	34, // 57: proto.static.Checks.Liveness:output_type -> proto.static.ChecksResponse
	34, // 58: proto.static.Checks.Readiness:output_type -> proto.static.ChecksResponse
	40, // [40:59] is the sub-list for method output_type
	21, // [21:40] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_research_pillars_static_static_proto_init() }
func file_research_pillars_static_static_proto_init() {
	if File_research_pillars_static_static_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_research_pillars_static_static_proto_rawDesc), len(file_research_pillars_static_static_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   9,
		},
		GoTypes:           file_research_pillars_static_static_proto_goTypes,
		DependencyIndexes: file_research_pillars_static_static_proto_depIdxs,
		MessageInfos:      file_research_pillars_static_static_proto_msgTypes,
	}.Build()
	File_research_pillars_static_static_proto = out.File
	file_research_pillars_static_static_proto_goTypes = nil
	file_research_pillars_static_static_proto_depIdxs = nil
}
