// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: research-pillars/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Users_GetSelf_FullMethodName            = "/proto.api.Users/GetSelf"
	Users_GetUsers_FullMethodName           = "/proto.api.Users/GetUsers"
	Users_UpsertProgramRole_FullMethodName  = "/proto.api.Users/UpsertProgramRole"
	Users_DeleteProgramRole_FullMethodName  = "/proto.api.Users/DeleteProgramRole"
	Users_GetBlockedPrograms_FullMethodName = "/proto.api.Users/GetBlockedPrograms"
	Users_BlockProgram_FullMethodName       = "/proto.api.Users/BlockProgram"
	Users_UnblockProgram_FullMethodName     = "/proto.api.Users/UnblockProgram"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	GetSelf(ctx context.Context, in *GetSelfRequest, opts ...grpc.CallOption) (*GetSelfResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	UpsertProgramRole(ctx context.Context, in *UpsertProgramRoleRequest, opts ...grpc.CallOption) (*UpsertProgramRoleResponse, error)
	DeleteProgramRole(ctx context.Context, in *DeleteProgramRoleRequest, opts ...grpc.CallOption) (*DeleteProgramRoleResponse, error)
	GetBlockedPrograms(ctx context.Context, in *GetBlockedProgramsRequest, opts ...grpc.CallOption) (*GetBlockedProgramsResponse, error)
	BlockProgram(ctx context.Context, in *BlockProgramRequest, opts ...grpc.CallOption) (*BlockProgramResponse, error)
	UnblockProgram(ctx context.Context, in *UnblockProgramRequest, opts ...grpc.CallOption) (*UnblockProgramResponse, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetSelf(ctx context.Context, in *GetSelfRequest, opts ...grpc.CallOption) (*GetSelfResponse, error) {
	out := new(GetSelfResponse)
	err := c.cc.Invoke(ctx, Users_GetSelf_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, Users_GetUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpsertProgramRole(ctx context.Context, in *UpsertProgramRoleRequest, opts ...grpc.CallOption) (*UpsertProgramRoleResponse, error) {
	out := new(UpsertProgramRoleResponse)
	err := c.cc.Invoke(ctx, Users_UpsertProgramRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteProgramRole(ctx context.Context, in *DeleteProgramRoleRequest, opts ...grpc.CallOption) (*DeleteProgramRoleResponse, error) {
	out := new(DeleteProgramRoleResponse)
	err := c.cc.Invoke(ctx, Users_DeleteProgramRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetBlockedPrograms(ctx context.Context, in *GetBlockedProgramsRequest, opts ...grpc.CallOption) (*GetBlockedProgramsResponse, error) {
	out := new(GetBlockedProgramsResponse)
	err := c.cc.Invoke(ctx, Users_GetBlockedPrograms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) BlockProgram(ctx context.Context, in *BlockProgramRequest, opts ...grpc.CallOption) (*BlockProgramResponse, error) {
	out := new(BlockProgramResponse)
	err := c.cc.Invoke(ctx, Users_BlockProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UnblockProgram(ctx context.Context, in *UnblockProgramRequest, opts ...grpc.CallOption) (*UnblockProgramResponse, error) {
	out := new(UnblockProgramResponse)
	err := c.cc.Invoke(ctx, Users_UnblockProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility
type UsersServer interface {
	GetSelf(context.Context, *GetSelfRequest) (*GetSelfResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	UpsertProgramRole(context.Context, *UpsertProgramRoleRequest) (*UpsertProgramRoleResponse, error)
	DeleteProgramRole(context.Context, *DeleteProgramRoleRequest) (*DeleteProgramRoleResponse, error)
	GetBlockedPrograms(context.Context, *GetBlockedProgramsRequest) (*GetBlockedProgramsResponse, error)
	BlockProgram(context.Context, *BlockProgramRequest) (*BlockProgramResponse, error)
	UnblockProgram(context.Context, *UnblockProgramRequest) (*UnblockProgramResponse, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (UnimplementedUsersServer) GetSelf(context.Context, *GetSelfRequest) (*GetSelfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelf not implemented")
}
func (UnimplementedUsersServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUsersServer) UpsertProgramRole(context.Context, *UpsertProgramRoleRequest) (*UpsertProgramRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProgramRole not implemented")
}
func (UnimplementedUsersServer) DeleteProgramRole(context.Context, *DeleteProgramRoleRequest) (*DeleteProgramRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProgramRole not implemented")
}
func (UnimplementedUsersServer) GetBlockedPrograms(context.Context, *GetBlockedProgramsRequest) (*GetBlockedProgramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockedPrograms not implemented")
}
func (UnimplementedUsersServer) BlockProgram(context.Context, *BlockProgramRequest) (*BlockProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockProgram not implemented")
}
func (UnimplementedUsersServer) UnblockProgram(context.Context, *UnblockProgramRequest) (*UnblockProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockProgram not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_GetSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetSelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetSelf(ctx, req.(*GetSelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpsertProgramRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProgramRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpsertProgramRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UpsertProgramRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpsertProgramRole(ctx, req.(*UpsertProgramRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteProgramRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProgramRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteProgramRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteProgramRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteProgramRole(ctx, req.(*DeleteProgramRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetBlockedPrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockedProgramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetBlockedPrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetBlockedPrograms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetBlockedPrograms(ctx, req.(*GetBlockedProgramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_BlockProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).BlockProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_BlockProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).BlockProgram(ctx, req.(*BlockProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UnblockProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UnblockProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UnblockProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UnblockProgram(ctx, req.(*UnblockProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.api.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSelf",
			Handler:    _Users_GetSelf_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Users_GetUsers_Handler,
		},
		{
			MethodName: "UpsertProgramRole",
			Handler:    _Users_UpsertProgramRole_Handler,
		},
		{
			MethodName: "DeleteProgramRole",
			Handler:    _Users_DeleteProgramRole_Handler,
		},
		{
			MethodName: "GetBlockedPrograms",
			Handler:    _Users_GetBlockedPrograms_Handler,
		},
		{
			MethodName: "BlockProgram",
			Handler:    _Users_BlockProgram_Handler,
		},
		{
			MethodName: "UnblockProgram",
			Handler:    _Users_UnblockProgram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "research-pillars/api/api.proto",
}

const (
	Programs_GetPrograms_FullMethodName     = "/proto.api.Programs/GetPrograms"
	Programs_GetProgramsList_FullMethodName = "/proto.api.Programs/GetProgramsList"
	Programs_GetProgram_FullMethodName      = "/proto.api.Programs/GetProgram"
	Programs_GetProgramData_FullMethodName  = "/proto.api.Programs/GetProgramData"
	Programs_UpsertProgram_FullMethodName   = "/proto.api.Programs/UpsertProgram"
	Programs_DeleteProgram_FullMethodName   = "/proto.api.Programs/DeleteProgram"
	Programs_PublishProgram_FullMethodName  = "/proto.api.Programs/PublishProgram"
	Programs_LoadProgram_FullMethodName     = "/proto.api.Programs/LoadProgram"
)

// ProgramsClient is the client API for Programs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramsClient interface {
	GetPrograms(ctx context.Context, in *GetProgramsRequest, opts ...grpc.CallOption) (*GetProgramsResponse, error)
	GetProgramsList(ctx context.Context, in *GetProgramsListRequest, opts ...grpc.CallOption) (*GetProgramsListResponse, error)
	GetProgram(ctx context.Context, in *GetProgramRequest, opts ...grpc.CallOption) (*GetProgramResponse, error)
	GetProgramData(ctx context.Context, in *GetProgramDataRequest, opts ...grpc.CallOption) (*GetProgramDataResponse, error)
	UpsertProgram(ctx context.Context, in *UpsertProgramRequest, opts ...grpc.CallOption) (*UpsertProgramResponse, error)
	DeleteProgram(ctx context.Context, in *DeleteProgramRequest, opts ...grpc.CallOption) (*DeleteProgramResponse, error)
	PublishProgram(ctx context.Context, in *PublishProgramRequest, opts ...grpc.CallOption) (*PublishProgramResponse, error)
	LoadProgram(ctx context.Context, in *LoadProgramRequest, opts ...grpc.CallOption) (*LoadProgramResponse, error)
}

type programsClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramsClient(cc grpc.ClientConnInterface) ProgramsClient {
	return &programsClient{cc}
}

func (c *programsClient) GetPrograms(ctx context.Context, in *GetProgramsRequest, opts ...grpc.CallOption) (*GetProgramsResponse, error) {
	out := new(GetProgramsResponse)
	err := c.cc.Invoke(ctx, Programs_GetPrograms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) GetProgramsList(ctx context.Context, in *GetProgramsListRequest, opts ...grpc.CallOption) (*GetProgramsListResponse, error) {
	out := new(GetProgramsListResponse)
	err := c.cc.Invoke(ctx, Programs_GetProgramsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) GetProgram(ctx context.Context, in *GetProgramRequest, opts ...grpc.CallOption) (*GetProgramResponse, error) {
	out := new(GetProgramResponse)
	err := c.cc.Invoke(ctx, Programs_GetProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) GetProgramData(ctx context.Context, in *GetProgramDataRequest, opts ...grpc.CallOption) (*GetProgramDataResponse, error) {
	out := new(GetProgramDataResponse)
	err := c.cc.Invoke(ctx, Programs_GetProgramData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) UpsertProgram(ctx context.Context, in *UpsertProgramRequest, opts ...grpc.CallOption) (*UpsertProgramResponse, error) {
	out := new(UpsertProgramResponse)
	err := c.cc.Invoke(ctx, Programs_UpsertProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) DeleteProgram(ctx context.Context, in *DeleteProgramRequest, opts ...grpc.CallOption) (*DeleteProgramResponse, error) {
	out := new(DeleteProgramResponse)
	err := c.cc.Invoke(ctx, Programs_DeleteProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) PublishProgram(ctx context.Context, in *PublishProgramRequest, opts ...grpc.CallOption) (*PublishProgramResponse, error) {
	out := new(PublishProgramResponse)
	err := c.cc.Invoke(ctx, Programs_PublishProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programsClient) LoadProgram(ctx context.Context, in *LoadProgramRequest, opts ...grpc.CallOption) (*LoadProgramResponse, error) {
	out := new(LoadProgramResponse)
	err := c.cc.Invoke(ctx, Programs_LoadProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramsServer is the server API for Programs service.
// All implementations must embed UnimplementedProgramsServer
// for forward compatibility
type ProgramsServer interface {
	GetPrograms(context.Context, *GetProgramsRequest) (*GetProgramsResponse, error)
	GetProgramsList(context.Context, *GetProgramsListRequest) (*GetProgramsListResponse, error)
	GetProgram(context.Context, *GetProgramRequest) (*GetProgramResponse, error)
	GetProgramData(context.Context, *GetProgramDataRequest) (*GetProgramDataResponse, error)
	UpsertProgram(context.Context, *UpsertProgramRequest) (*UpsertProgramResponse, error)
	DeleteProgram(context.Context, *DeleteProgramRequest) (*DeleteProgramResponse, error)
	PublishProgram(context.Context, *PublishProgramRequest) (*PublishProgramResponse, error)
	LoadProgram(context.Context, *LoadProgramRequest) (*LoadProgramResponse, error)
	mustEmbedUnimplementedProgramsServer()
}

// UnimplementedProgramsServer must be embedded to have forward compatible implementations.
type UnimplementedProgramsServer struct {
}

func (UnimplementedProgramsServer) GetPrograms(context.Context, *GetProgramsRequest) (*GetProgramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrograms not implemented")
}
func (UnimplementedProgramsServer) GetProgramsList(context.Context, *GetProgramsListRequest) (*GetProgramsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgramsList not implemented")
}
func (UnimplementedProgramsServer) GetProgram(context.Context, *GetProgramRequest) (*GetProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgram not implemented")
}
func (UnimplementedProgramsServer) GetProgramData(context.Context, *GetProgramDataRequest) (*GetProgramDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgramData not implemented")
}
func (UnimplementedProgramsServer) UpsertProgram(context.Context, *UpsertProgramRequest) (*UpsertProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProgram not implemented")
}
func (UnimplementedProgramsServer) DeleteProgram(context.Context, *DeleteProgramRequest) (*DeleteProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProgram not implemented")
}
func (UnimplementedProgramsServer) PublishProgram(context.Context, *PublishProgramRequest) (*PublishProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishProgram not implemented")
}
func (UnimplementedProgramsServer) LoadProgram(context.Context, *LoadProgramRequest) (*LoadProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadProgram not implemented")
}
func (UnimplementedProgramsServer) mustEmbedUnimplementedProgramsServer() {}

// UnsafeProgramsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramsServer will
// result in compilation errors.
type UnsafeProgramsServer interface {
	mustEmbedUnimplementedProgramsServer()
}

func RegisterProgramsServer(s grpc.ServiceRegistrar, srv ProgramsServer) {
	s.RegisterService(&Programs_ServiceDesc, srv)
}

func _Programs_GetPrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).GetPrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_GetPrograms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).GetPrograms(ctx, req.(*GetProgramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_GetProgramsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).GetProgramsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_GetProgramsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).GetProgramsList(ctx, req.(*GetProgramsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_GetProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).GetProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_GetProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).GetProgram(ctx, req.(*GetProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_GetProgramData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).GetProgramData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_GetProgramData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).GetProgramData(ctx, req.(*GetProgramDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_UpsertProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).UpsertProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_UpsertProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).UpsertProgram(ctx, req.(*UpsertProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_DeleteProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).DeleteProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_DeleteProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).DeleteProgram(ctx, req.(*DeleteProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_PublishProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).PublishProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_PublishProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).PublishProgram(ctx, req.(*PublishProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Programs_LoadProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramsServer).LoadProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Programs_LoadProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramsServer).LoadProgram(ctx, req.(*LoadProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Programs_ServiceDesc is the grpc.ServiceDesc for Programs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Programs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.api.Programs",
	HandlerType: (*ProgramsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrograms",
			Handler:    _Programs_GetPrograms_Handler,
		},
		{
			MethodName: "GetProgramsList",
			Handler:    _Programs_GetProgramsList_Handler,
		},
		{
			MethodName: "GetProgram",
			Handler:    _Programs_GetProgram_Handler,
		},
		{
			MethodName: "GetProgramData",
			Handler:    _Programs_GetProgramData_Handler,
		},
		{
			MethodName: "UpsertProgram",
			Handler:    _Programs_UpsertProgram_Handler,
		},
		{
			MethodName: "DeleteProgram",
			Handler:    _Programs_DeleteProgram_Handler,
		},
		{
			MethodName: "PublishProgram",
			Handler:    _Programs_PublishProgram_Handler,
		},
		{
			MethodName: "LoadProgram",
			Handler:    _Programs_LoadProgram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "research-pillars/api/api.proto",
}

const (
	Surveys_GetSurveys_FullMethodName    = "/proto.api.Surveys/GetSurveys"
	Surveys_GetSurvey_FullMethodName     = "/proto.api.Surveys/GetSurvey"
	Surveys_UpsertSurvey_FullMethodName  = "/proto.api.Surveys/UpsertSurvey"
	Surveys_DeleteSurvey_FullMethodName  = "/proto.api.Surveys/DeleteSurvey"
	Surveys_PublishSurvey_FullMethodName = "/proto.api.Surveys/PublishSurvey"
	Surveys_LoadSurvey_FullMethodName    = "/proto.api.Surveys/LoadSurvey"
)

// SurveysClient is the client API for Surveys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SurveysClient interface {
	GetSurveys(ctx context.Context, in *GetSurveysRequest, opts ...grpc.CallOption) (*GetSurveysResponse, error)
	GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*GetSurveyResponse, error)
	UpsertSurvey(ctx context.Context, in *UpsertSurveyRequest, opts ...grpc.CallOption) (*UpsertSurveyResponse, error)
	DeleteSurvey(ctx context.Context, in *DeleteSurveyRequest, opts ...grpc.CallOption) (*DeleteSurveyResponse, error)
	PublishSurvey(ctx context.Context, in *PublishSurveyRequest, opts ...grpc.CallOption) (*PublishSurveyResponse, error)
	LoadSurvey(ctx context.Context, in *LoadSurveyRequest, opts ...grpc.CallOption) (*LoadSurveyResponse, error)
}

type surveysClient struct {
	cc grpc.ClientConnInterface
}

func NewSurveysClient(cc grpc.ClientConnInterface) SurveysClient {
	return &surveysClient{cc}
}

func (c *surveysClient) GetSurveys(ctx context.Context, in *GetSurveysRequest, opts ...grpc.CallOption) (*GetSurveysResponse, error) {
	out := new(GetSurveysResponse)
	err := c.cc.Invoke(ctx, Surveys_GetSurveys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*GetSurveyResponse, error) {
	out := new(GetSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_GetSurvey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) UpsertSurvey(ctx context.Context, in *UpsertSurveyRequest, opts ...grpc.CallOption) (*UpsertSurveyResponse, error) {
	out := new(UpsertSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_UpsertSurvey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) DeleteSurvey(ctx context.Context, in *DeleteSurveyRequest, opts ...grpc.CallOption) (*DeleteSurveyResponse, error) {
	out := new(DeleteSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_DeleteSurvey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) PublishSurvey(ctx context.Context, in *PublishSurveyRequest, opts ...grpc.CallOption) (*PublishSurveyResponse, error) {
	out := new(PublishSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_PublishSurvey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) LoadSurvey(ctx context.Context, in *LoadSurveyRequest, opts ...grpc.CallOption) (*LoadSurveyResponse, error) {
	out := new(LoadSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_LoadSurvey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurveysServer is the server API for Surveys service.
// All implementations must embed UnimplementedSurveysServer
// for forward compatibility
type SurveysServer interface {
	GetSurveys(context.Context, *GetSurveysRequest) (*GetSurveysResponse, error)
	GetSurvey(context.Context, *GetSurveyRequest) (*GetSurveyResponse, error)
	UpsertSurvey(context.Context, *UpsertSurveyRequest) (*UpsertSurveyResponse, error)
	DeleteSurvey(context.Context, *DeleteSurveyRequest) (*DeleteSurveyResponse, error)
	PublishSurvey(context.Context, *PublishSurveyRequest) (*PublishSurveyResponse, error)
	LoadSurvey(context.Context, *LoadSurveyRequest) (*LoadSurveyResponse, error)
	mustEmbedUnimplementedSurveysServer()
}

// UnimplementedSurveysServer must be embedded to have forward compatible implementations.
type UnimplementedSurveysServer struct {
}

func (UnimplementedSurveysServer) GetSurveys(context.Context, *GetSurveysRequest) (*GetSurveysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSurveys not implemented")
}
func (UnimplementedSurveysServer) GetSurvey(context.Context, *GetSurveyRequest) (*GetSurveyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSurvey not implemented")
}
func (UnimplementedSurveysServer) UpsertSurvey(context.Context, *UpsertSurveyRequest) (*UpsertSurveyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSurvey not implemented")
}
func (UnimplementedSurveysServer) DeleteSurvey(context.Context, *DeleteSurveyRequest) (*DeleteSurveyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSurvey not implemented")
}
func (UnimplementedSurveysServer) PublishSurvey(context.Context, *PublishSurveyRequest) (*PublishSurveyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishSurvey not implemented")
}
func (UnimplementedSurveysServer) LoadSurvey(context.Context, *LoadSurveyRequest) (*LoadSurveyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSurvey not implemented")
}
func (UnimplementedSurveysServer) mustEmbedUnimplementedSurveysServer() {}

// UnsafeSurveysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SurveysServer will
// result in compilation errors.
type UnsafeSurveysServer interface {
	mustEmbedUnimplementedSurveysServer()
}

func RegisterSurveysServer(s grpc.ServiceRegistrar, srv SurveysServer) {
	s.RegisterService(&Surveys_ServiceDesc, srv)
}

func _Surveys_GetSurveys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).GetSurveys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_GetSurveys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).GetSurveys(ctx, req.(*GetSurveysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_GetSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).GetSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_GetSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).GetSurvey(ctx, req.(*GetSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_UpsertSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).UpsertSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_UpsertSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).UpsertSurvey(ctx, req.(*UpsertSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_DeleteSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).DeleteSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_DeleteSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).DeleteSurvey(ctx, req.(*DeleteSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_PublishSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).PublishSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_PublishSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).PublishSurvey(ctx, req.(*PublishSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_LoadSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).LoadSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_LoadSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).LoadSurvey(ctx, req.(*LoadSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Surveys_ServiceDesc is the grpc.ServiceDesc for Surveys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Surveys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.api.Surveys",
	HandlerType: (*SurveysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSurveys",
			Handler:    _Surveys_GetSurveys_Handler,
		},
		{
			MethodName: "GetSurvey",
			Handler:    _Surveys_GetSurvey_Handler,
		},
		{
			MethodName: "UpsertSurvey",
			Handler:    _Surveys_UpsertSurvey_Handler,
		},
		{
			MethodName: "DeleteSurvey",
			Handler:    _Surveys_DeleteSurvey_Handler,
		},
		{
			MethodName: "PublishSurvey",
			Handler:    _Surveys_PublishSurvey_Handler,
		},
		{
			MethodName: "LoadSurvey",
			Handler:    _Surveys_LoadSurvey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "research-pillars/api/api.proto",
}

const (
	Questionnaires_GetQuestionnaires_FullMethodName    = "/proto.api.Questionnaires/GetQuestionnaires"
	Questionnaires_GetQuestionnaire_FullMethodName     = "/proto.api.Questionnaires/GetQuestionnaire"
	Questionnaires_UpsertQuestionnaire_FullMethodName  = "/proto.api.Questionnaires/UpsertQuestionnaire"
	Questionnaires_DeleteQuestionnaire_FullMethodName  = "/proto.api.Questionnaires/DeleteQuestionnaire"
	Questionnaires_PublishQuestionnaire_FullMethodName = "/proto.api.Questionnaires/PublishQuestionnaire"
	Questionnaires_LoadQuestionnaire_FullMethodName    = "/proto.api.Questionnaires/LoadQuestionnaire"
)

// QuestionnairesClient is the client API for Questionnaires service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestionnairesClient interface {
	GetQuestionnaires(ctx context.Context, in *GetQuestionnairesRequest, opts ...grpc.CallOption) (*GetQuestionnairesResponse, error)
	GetQuestionnaire(ctx context.Context, in *GetQuestionnaireRequest, opts ...grpc.CallOption) (*GetQuestionnaireResponse, error)
	UpsertQuestionnaire(ctx context.Context, in *UpsertQuestionnaireRequest, opts ...grpc.CallOption) (*UpsertQuestionnaireResponse, error)
	DeleteQuestionnaire(ctx context.Context, in *DeleteQuestionnaireRequest, opts ...grpc.CallOption) (*DeleteQuestionnaireResponse, error)
	PublishQuestionnaire(ctx context.Context, in *PublishQuestionnaireRequest, opts ...grpc.CallOption) (*PublishQuestionnaireResponse, error)
	LoadQuestionnaire(ctx context.Context, in *LoadQuestionnaireRequest, opts ...grpc.CallOption) (*LoadQuestionnaireResponse, error)
}

type questionnairesClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionnairesClient(cc grpc.ClientConnInterface) QuestionnairesClient {
	return &questionnairesClient{cc}
}

func (c *questionnairesClient) GetQuestionnaires(ctx context.Context, in *GetQuestionnairesRequest, opts ...grpc.CallOption) (*GetQuestionnairesResponse, error) {
	out := new(GetQuestionnairesResponse)
	err := c.cc.Invoke(ctx, Questionnaires_GetQuestionnaires_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionnairesClient) GetQuestionnaire(ctx context.Context, in *GetQuestionnaireRequest, opts ...grpc.CallOption) (*GetQuestionnaireResponse, error) {
	out := new(GetQuestionnaireResponse)
	err := c.cc.Invoke(ctx, Questionnaires_GetQuestionnaire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionnairesClient) UpsertQuestionnaire(ctx context.Context, in *UpsertQuestionnaireRequest, opts ...grpc.CallOption) (*UpsertQuestionnaireResponse, error) {
	out := new(UpsertQuestionnaireResponse)
	err := c.cc.Invoke(ctx, Questionnaires_UpsertQuestionnaire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionnairesClient) DeleteQuestionnaire(ctx context.Context, in *DeleteQuestionnaireRequest, opts ...grpc.CallOption) (*DeleteQuestionnaireResponse, error) {
	out := new(DeleteQuestionnaireResponse)
	err := c.cc.Invoke(ctx, Questionnaires_DeleteQuestionnaire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionnairesClient) PublishQuestionnaire(ctx context.Context, in *PublishQuestionnaireRequest, opts ...grpc.CallOption) (*PublishQuestionnaireResponse, error) {
	out := new(PublishQuestionnaireResponse)
	err := c.cc.Invoke(ctx, Questionnaires_PublishQuestionnaire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionnairesClient) LoadQuestionnaire(ctx context.Context, in *LoadQuestionnaireRequest, opts ...grpc.CallOption) (*LoadQuestionnaireResponse, error) {
	out := new(LoadQuestionnaireResponse)
	err := c.cc.Invoke(ctx, Questionnaires_LoadQuestionnaire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionnairesServer is the server API for Questionnaires service.
// All implementations must embed UnimplementedQuestionnairesServer
// for forward compatibility
type QuestionnairesServer interface {
	GetQuestionnaires(context.Context, *GetQuestionnairesRequest) (*GetQuestionnairesResponse, error)
	GetQuestionnaire(context.Context, *GetQuestionnaireRequest) (*GetQuestionnaireResponse, error)
	UpsertQuestionnaire(context.Context, *UpsertQuestionnaireRequest) (*UpsertQuestionnaireResponse, error)
	DeleteQuestionnaire(context.Context, *DeleteQuestionnaireRequest) (*DeleteQuestionnaireResponse, error)
	PublishQuestionnaire(context.Context, *PublishQuestionnaireRequest) (*PublishQuestionnaireResponse, error)
	LoadQuestionnaire(context.Context, *LoadQuestionnaireRequest) (*LoadQuestionnaireResponse, error)
	mustEmbedUnimplementedQuestionnairesServer()
}

// UnimplementedQuestionnairesServer must be embedded to have forward compatible implementations.
type UnimplementedQuestionnairesServer struct {
}

func (UnimplementedQuestionnairesServer) GetQuestionnaires(context.Context, *GetQuestionnairesRequest) (*GetQuestionnairesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionnaires not implemented")
}
func (UnimplementedQuestionnairesServer) GetQuestionnaire(context.Context, *GetQuestionnaireRequest) (*GetQuestionnaireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionnaire not implemented")
}
func (UnimplementedQuestionnairesServer) UpsertQuestionnaire(context.Context, *UpsertQuestionnaireRequest) (*UpsertQuestionnaireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertQuestionnaire not implemented")
}
func (UnimplementedQuestionnairesServer) DeleteQuestionnaire(context.Context, *DeleteQuestionnaireRequest) (*DeleteQuestionnaireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuestionnaire not implemented")
}
func (UnimplementedQuestionnairesServer) PublishQuestionnaire(context.Context, *PublishQuestionnaireRequest) (*PublishQuestionnaireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishQuestionnaire not implemented")
}
func (UnimplementedQuestionnairesServer) LoadQuestionnaire(context.Context, *LoadQuestionnaireRequest) (*LoadQuestionnaireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadQuestionnaire not implemented")
}
func (UnimplementedQuestionnairesServer) mustEmbedUnimplementedQuestionnairesServer() {}

// UnsafeQuestionnairesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionnairesServer will
// result in compilation errors.
type UnsafeQuestionnairesServer interface {
	mustEmbedUnimplementedQuestionnairesServer()
}

func RegisterQuestionnairesServer(s grpc.ServiceRegistrar, srv QuestionnairesServer) {
	s.RegisterService(&Questionnaires_ServiceDesc, srv)
}

func _Questionnaires_GetQuestionnaires_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionnairesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionnairesServer).GetQuestionnaires(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Questionnaires_GetQuestionnaires_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionnairesServer).GetQuestionnaires(ctx, req.(*GetQuestionnairesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questionnaires_GetQuestionnaire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionnaireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionnairesServer).GetQuestionnaire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Questionnaires_GetQuestionnaire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionnairesServer).GetQuestionnaire(ctx, req.(*GetQuestionnaireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questionnaires_UpsertQuestionnaire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertQuestionnaireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionnairesServer).UpsertQuestionnaire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Questionnaires_UpsertQuestionnaire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionnairesServer).UpsertQuestionnaire(ctx, req.(*UpsertQuestionnaireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questionnaires_DeleteQuestionnaire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestionnaireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionnairesServer).DeleteQuestionnaire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Questionnaires_DeleteQuestionnaire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionnairesServer).DeleteQuestionnaire(ctx, req.(*DeleteQuestionnaireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questionnaires_PublishQuestionnaire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishQuestionnaireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionnairesServer).PublishQuestionnaire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Questionnaires_PublishQuestionnaire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionnairesServer).PublishQuestionnaire(ctx, req.(*PublishQuestionnaireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questionnaires_LoadQuestionnaire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadQuestionnaireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionnairesServer).LoadQuestionnaire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Questionnaires_LoadQuestionnaire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionnairesServer).LoadQuestionnaire(ctx, req.(*LoadQuestionnaireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Questionnaires_ServiceDesc is the grpc.ServiceDesc for Questionnaires service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Questionnaires_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.api.Questionnaires",
	HandlerType: (*QuestionnairesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuestionnaires",
			Handler:    _Questionnaires_GetQuestionnaires_Handler,
		},
		{
			MethodName: "GetQuestionnaire",
			Handler:    _Questionnaires_GetQuestionnaire_Handler,
		},
		{
			MethodName: "UpsertQuestionnaire",
			Handler:    _Questionnaires_UpsertQuestionnaire_Handler,
		},
		{
			MethodName: "DeleteQuestionnaire",
			Handler:    _Questionnaires_DeleteQuestionnaire_Handler,
		},
		{
			MethodName: "PublishQuestionnaire",
			Handler:    _Questionnaires_PublishQuestionnaire_Handler,
		},
		{
			MethodName: "LoadQuestionnaire",
			Handler:    _Questionnaires_LoadQuestionnaire_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "research-pillars/api/api.proto",
}

const (
	ParticipantCodes_GetCodes_FullMethodName      = "/proto.api.ParticipantCodes/GetCodes"
	ParticipantCodes_GenerateCodes_FullMethodName = "/proto.api.ParticipantCodes/GenerateCodes"
	ParticipantCodes_AssignCode_FullMethodName    = "/proto.api.ParticipantCodes/AssignCode"
	ParticipantCodes_DeleteCode_FullMethodName    = "/proto.api.ParticipantCodes/DeleteCode"
	ParticipantCodes_UnassignCode_FullMethodName  = "/proto.api.ParticipantCodes/UnassignCode"
)

// ParticipantCodesClient is the client API for ParticipantCodes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParticipantCodesClient interface {
	GetCodes(ctx context.Context, in *GetCodesRequest, opts ...grpc.CallOption) (*GetCodesResponse, error)
	GenerateCodes(ctx context.Context, in *GenerateCodesRequest, opts ...grpc.CallOption) (*GenerateCodesResponse, error)
	AssignCode(ctx context.Context, in *AssignCodeRequest, opts ...grpc.CallOption) (*AssignCodeResponse, error)
	DeleteCode(ctx context.Context, in *DeleteCodeRequest, opts ...grpc.CallOption) (*DeleteCodeResponse, error)
	UnassignCode(ctx context.Context, in *UnassignCodeRequest, opts ...grpc.CallOption) (*UnassignCodeResponse, error)
}

type participantCodesClient struct {
	cc grpc.ClientConnInterface
}

func NewParticipantCodesClient(cc grpc.ClientConnInterface) ParticipantCodesClient {
	return &participantCodesClient{cc}
}

func (c *participantCodesClient) GetCodes(ctx context.Context, in *GetCodesRequest, opts ...grpc.CallOption) (*GetCodesResponse, error) {
	out := new(GetCodesResponse)
	err := c.cc.Invoke(ctx, ParticipantCodes_GetCodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantCodesClient) GenerateCodes(ctx context.Context, in *GenerateCodesRequest, opts ...grpc.CallOption) (*GenerateCodesResponse, error) {
	out := new(GenerateCodesResponse)
	err := c.cc.Invoke(ctx, ParticipantCodes_GenerateCodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantCodesClient) AssignCode(ctx context.Context, in *AssignCodeRequest, opts ...grpc.CallOption) (*AssignCodeResponse, error) {
	out := new(AssignCodeResponse)
	err := c.cc.Invoke(ctx, ParticipantCodes_AssignCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantCodesClient) DeleteCode(ctx context.Context, in *DeleteCodeRequest, opts ...grpc.CallOption) (*DeleteCodeResponse, error) {
	out := new(DeleteCodeResponse)
	err := c.cc.Invoke(ctx, ParticipantCodes_DeleteCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantCodesClient) UnassignCode(ctx context.Context, in *UnassignCodeRequest, opts ...grpc.CallOption) (*UnassignCodeResponse, error) {
	out := new(UnassignCodeResponse)
	err := c.cc.Invoke(ctx, ParticipantCodes_UnassignCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParticipantCodesServer is the server API for ParticipantCodes service.
// All implementations must embed UnimplementedParticipantCodesServer
// for forward compatibility
type ParticipantCodesServer interface {
	GetCodes(context.Context, *GetCodesRequest) (*GetCodesResponse, error)
	GenerateCodes(context.Context, *GenerateCodesRequest) (*GenerateCodesResponse, error)
	AssignCode(context.Context, *AssignCodeRequest) (*AssignCodeResponse, error)
	DeleteCode(context.Context, *DeleteCodeRequest) (*DeleteCodeResponse, error)
	UnassignCode(context.Context, *UnassignCodeRequest) (*UnassignCodeResponse, error)
	mustEmbedUnimplementedParticipantCodesServer()
}

// UnimplementedParticipantCodesServer must be embedded to have forward compatible implementations.
type UnimplementedParticipantCodesServer struct {
}

func (UnimplementedParticipantCodesServer) GetCodes(context.Context, *GetCodesRequest) (*GetCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodes not implemented")
}
func (UnimplementedParticipantCodesServer) GenerateCodes(context.Context, *GenerateCodesRequest) (*GenerateCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCodes not implemented")
}
func (UnimplementedParticipantCodesServer) AssignCode(context.Context, *AssignCodeRequest) (*AssignCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignCode not implemented")
}
func (UnimplementedParticipantCodesServer) DeleteCode(context.Context, *DeleteCodeRequest) (*DeleteCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCode not implemented")
}
func (UnimplementedParticipantCodesServer) UnassignCode(context.Context, *UnassignCodeRequest) (*UnassignCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignCode not implemented")
}
func (UnimplementedParticipantCodesServer) mustEmbedUnimplementedParticipantCodesServer() {}

// UnsafeParticipantCodesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParticipantCodesServer will
// result in compilation errors.
type UnsafeParticipantCodesServer interface {
	mustEmbedUnimplementedParticipantCodesServer()
}

func RegisterParticipantCodesServer(s grpc.ServiceRegistrar, srv ParticipantCodesServer) {
	s.RegisterService(&ParticipantCodes_ServiceDesc, srv)
}

func _ParticipantCodes_GetCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantCodesServer).GetCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipantCodes_GetCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantCodesServer).GetCodes(ctx, req.(*GetCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticipantCodes_GenerateCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantCodesServer).GenerateCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipantCodes_GenerateCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantCodesServer).GenerateCodes(ctx, req.(*GenerateCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticipantCodes_AssignCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantCodesServer).AssignCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipantCodes_AssignCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantCodesServer).AssignCode(ctx, req.(*AssignCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticipantCodes_DeleteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantCodesServer).DeleteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipantCodes_DeleteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantCodesServer).DeleteCode(ctx, req.(*DeleteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticipantCodes_UnassignCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantCodesServer).UnassignCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipantCodes_UnassignCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantCodesServer).UnassignCode(ctx, req.(*UnassignCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParticipantCodes_ServiceDesc is the grpc.ServiceDesc for ParticipantCodes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParticipantCodes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.api.ParticipantCodes",
	HandlerType: (*ParticipantCodesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCodes",
			Handler:    _ParticipantCodes_GetCodes_Handler,
		},
		{
			MethodName: "GenerateCodes",
			Handler:    _ParticipantCodes_GenerateCodes_Handler,
		},
		{
			MethodName: "AssignCode",
			Handler:    _ParticipantCodes_AssignCode_Handler,
		},
		{
			MethodName: "DeleteCode",
			Handler:    _ParticipantCodes_DeleteCode_Handler,
		},
		{
			MethodName: "UnassignCode",
			Handler:    _ParticipantCodes_UnassignCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "research-pillars/api/api.proto",
}
